from cott_runtime import CottList
from real.harlequin.render_types import Theme


def bundled_themes() -> CottList[Theme]:
    return CottList(
        values=[
            Theme(
                name="harlequin",
                foreground="#DDDDDD",
                background="#0C0C0C",
                accent="#FFB6D9",
            ),
            Theme(
                name="textual-dark",
                foreground="#e0e0e0",
                background="#121212",
                accent="#ffa62b",
            ),
            Theme(
                name="textual-light",
                foreground="#1F1F1F",
                background="#E0E0E0",
                accent="#ffa62b",
            ),
            Theme(
                name="nord",
                foreground="#D8DEE9",
                background="#2E3440",
                accent="#B48EAD",
            ),
            Theme(
                name="gruvbox",
                foreground="#fbf1c7",
                background="#282828",
                accent="#fabd2f",
            ),
            Theme(
                name="catppuccin-mocha",
                foreground="#cdd6f4",
                background="#181825",
                accent="#fab387",
            ),
            Theme(
                name="dracula",
                foreground="#F8F8F2",
                background="#282A36",
                accent="#FF79C6",
            ),
            Theme(
                name="tokyo-night",
                foreground="#a9b1d6",
                background="#1A1B26",
                accent="#FF9E64",
            ),
            Theme(
                name="monokai",
                foreground="#d6d6d6",
                background="#272822",
                accent="#66D9EF",
            ),
            Theme(
                name="flexoki",
                foreground="#FFFCF0",
                background="#100F0F",
                accent="#9B76C8",
            ),
            Theme(
                name="catppuccin-latte",
                foreground="#4C4F69",
                background="#EFF1F5",
                accent="#FE640B",
            ),
            Theme(
                name="solarized-light",
                foreground="#586e75",
                background="#fdf6e3",
                accent="#6c71c4",
            ),
        ]
    )
