use std::collections::BTreeMap;
use std::path::PathBuf;

pub fn render_runtime(project_name: &str, project_version: &str) -> BTreeMap<PathBuf, Vec<u8>> {
    let source = format!(
        "// Generated by Cott. Do not edit.\npub const PROJECT_NAME: &str = {:?};\npub const PROJECT_VERSION: &str = {:?};\n{}",
        project_name, project_version, RUNTIME
    );
    BTreeMap::from([(
        PathBuf::from("rust/src/cott_runtime.rs"),
        source.into_bytes(),
    )])
}
const RUNTIME: &str = concat!(
    r#"
use std::future::Future;
use std::pin::Pin;
use std::sync::Arc;

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ContractViolation { pub symbol: String, pub phase: String, pub clause: String }
impl std::fmt::Display for ContractViolation {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result { write!(f, "{}: {} {}", self.symbol, self.phase, self.clause) }
}
impl std::error::Error for ContractViolation {}
pub fn violation(symbol: &str, phase: &str, clause: &str) -> ! {
    std::panic::panic_any(ContractViolation { symbol: symbol.to_owned(), phase: phase.to_owned(), clause: clause.to_owned() })
}
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Never {}
#[derive(Clone, Debug, PartialEq)]
pub enum JsonValue { Null, Bool(bool), Integer(i128), Number(f64), String(String), Array(Vec<JsonValue>), Object(std::collections::BTreeMap<String, JsonValue>) }
"#,
    include_str!("runtime/any.rs"),
    include_str!("runtime/collections.rs"),
    include_str!("runtime/protocols.rs"),
    r#"

pub fn math_add(a:i128,b:i128)->i128{a.checked_add(b).unwrap_or_else(||violation("arithmetic","validation","mathematical integer overflow"))}
pub fn math_sub(a:i128,b:i128)->i128{a.checked_sub(b).unwrap_or_else(||violation("arithmetic","validation","mathematical integer overflow"))}
pub fn math_mul(a:i128,b:i128)->i128{a.checked_mul(b).unwrap_or_else(||violation("arithmetic","validation","mathematical integer overflow"))}
pub fn math_neg(a:i128)->i128{a.checked_neg().unwrap_or_else(||violation("arithmetic","validation","mathematical integer overflow"))}
pub fn math_div(a:i128,b:i128)->i128{a.checked_div_euclid(b).unwrap_or_else(||violation("arithmetic","validation","invalid division"))}
pub fn math_rem(a:i128,b:i128)->i128{a.checked_rem_euclid(b).unwrap_or_else(||violation("arithmetic","validation","invalid remainder"))}
pub fn white_space(c:char)->bool{matches!(c,'\u{0009}'..='\u{000D}'|'\u{0020}'|'\u{0085}'|'\u{00A0}'|'\u{1680}'|'\u{2000}'..='\u{200A}'|'\u{2028}'|'\u{2029}'|'\u{202F}'|'\u{205F}'|'\u{3000}')}
pub fn unique_by<T,K:PartialEq>(values:&[T],key:impl Fn(&T)->&K)->bool{values.iter().enumerate().all(|(i,v)|values[..i].iter().all(|p|key(p)!=key(v)))}
pub fn permutation_by<T,K:PartialEq>(a:&[T],b:&[T],key:impl Fn(&T)->&K)->bool{a.len()==b.len()&&a.iter().all(|v|a.iter().filter(|x|key(x)==key(v)).count()==b.iter().filter(|x|key(x)==key(v)).count())}
pub fn unknown_dependency_by<T,K:PartialEq>(values:&[T],key:impl Fn(&T)->&K,deps:impl Fn(&T)->&Vec<K>)->bool{values.iter().any(|v|deps(v).iter().any(|d|!values.iter().any(|x|key(x)==d)))}
pub fn self_dependency_by<T,K:PartialEq>(values:&[T],key:impl Fn(&T)->&K,deps:impl Fn(&T)->&Vec<K>)->bool{values.iter().any(|v|deps(v).contains(key(v)))}
pub fn cyclic_by<T,K:PartialEq>(values:&[T],key:impl Fn(&T)->&K,deps:impl Fn(&T)->&Vec<K>)->bool{
 fn visit<T,K:PartialEq>(i:usize,v:&[T],key:&impl Fn(&T)->&K,deps:&impl Fn(&T)->&Vec<K>,marks:&mut[u8])->bool{if marks[i]==1{return true}if marks[i]==2{return false}marks[i]=1;for d in deps(&v[i]){if let Some(j)=v.iter().position(|x|key(x)==d){if visit(j,v,key,deps,marks){return true}}}marks[i]=2;false}
 let mut marks=vec![0;values.len()];(0..values.len()).any(|i|visit(i,values,&key,&deps,&mut marks))
}
pub fn dependency_ordered_by<T,K:PartialEq>(input:&[T],output:&[T],key:impl Fn(&T)->&K,deps:impl Fn(&T)->&Vec<K>)->bool{permutation_by(input,output,&key)&&output.iter().enumerate().all(|(i,v)|deps(v).iter().all(|d|output[..i].iter().any(|x|key(x)==d)))}

"#,
    include_str!("runtime/graph.rs"),
    include_str!("runtime/tasks.rs"),
    r#"

// Compiler-only evidence. Authored implementation audits deny these identifiers.
#[derive(Clone,Debug)]
pub struct PredicateObservation{pub symbol:String,pub clause:String,pub phase:String,pub passed:bool}
thread_local!{static OBSERVER:std::cell::RefCell<Option<Vec<PredicateObservation>>>=const{std::cell::RefCell::new(None)};static VALIDATION:std::cell::Cell<bool>=const{std::cell::Cell::new(false)};}
#[doc(hidden)]
pub fn __cott_observe_begin(){OBSERVER.with(|o|*o.borrow_mut()=Some(Vec::new()));VALIDATION.with(|v|v.set(true));}
#[doc(hidden)]
pub fn __cott_observe_end()->Vec<PredicateObservation>{VALIDATION.with(|v|v.set(false));OBSERVER.with(|o|o.borrow_mut().take().unwrap_or_default())}
#[doc(hidden)]
pub fn __cott_validation_enabled(boundary:bool)->bool{boundary||ASYNC_OBSERVER.try_with(|_|true).unwrap_or(false)||VALIDATION.with(|v|v.get())}
#[doc(hidden)]
pub fn __cott_check(symbol:&str,phase:&str,clause:&str,passed:bool){let event=||PredicateObservation{symbol:symbol.into(),clause:clause.into(),phase:phase.into(),passed};if ASYNC_OBSERVER.try_with(|o|o.lock().expect("observation sink").push(event())).is_err(){OBSERVER.with(|o|{if let Some(events)=o.borrow_mut().as_mut(){events.push(event())}});}if !passed{violation(symbol,phase,clause)}}
tokio::task_local!{static ASYNC_OBSERVER:Arc<std::sync::Mutex<Vec<PredicateObservation>>>;}
#[doc(hidden)]
pub async fn __cott_observe_async<F:Future>(future:F)->(Result<F::Output,Box<dyn std::any::Any+Send>>,Vec<PredicateObservation>){
 let sink=Arc::new(std::sync::Mutex::new(Vec::new()));
 let result=ASYNC_OBSERVER.scope(sink.clone(),async move {
  let mut future=std::pin::pin!(future);
  std::future::poll_fn(|cx|match std::panic::catch_unwind(std::panic::AssertUnwindSafe(||future.as_mut().poll(cx))){Ok(std::task::Poll::Ready(value))=>std::task::Poll::Ready(Ok(value)),Ok(std::task::Poll::Pending)=>std::task::Poll::Pending,Err(error)=>std::task::Poll::Ready(Err(error))}).await
 }).await;
 let events=std::mem::take(&mut *sink.lock().expect("observation sink"));(result,events)
}
"#,
    include_str!("runtime/value.rs"),
    include_str!("runtime/dimensions.rs"),
    r#"
mod resource_impl {
// Optional compiler-only capabilities are available even in packages without resources.
#![allow(dead_code)]
use super::*;
"#,
    include_str!("runtime/state.rs"),
    r#"
}
pub use resource_impl::ReadField;
#[allow(unused_imports)]
pub(crate) use resource_impl::{StateGate,__cott_state_enter,__cott_state_enter_async,__cott_with_state,__cott_with_state_async,__cott_state_write,__cott_validate_state,__cott_state_equal,__cott_snapshot_state};
"#
);
