const TRACEABILITY: &[(u8, &[&str])] = &[
    (
        1,
        &["cli::process_bar_generation_records_unresolved_and_verified_transitions"],
    ),
    (
        2,
        &[
            "semantic::rejects_module_path_mismatch",
            "python_emit::rejects_colliding_public_python_symbol_projection",
        ],
    ),
    (
        3,
        &[
            "compiler::aggregates_syntax_diagnostics_with_their_source_paths",
            "diagnostics::report_is_one_json_object_with_source_locations",
        ],
    ),
    (
        4,
        &[
            "ir::checked_in_canonical_ir_schema_is_parseable",
            "hir::direct_lowering_preserves_parsed_owned_structure_and_contracts",
        ],
    ),
    (
        5,
        &["semantic::preserves_cross_module_clause_variant_identity"],
    ),
    (
        6,
        &[
            "python_emit::imports_cross_module_contract_constants",
            "python_emit::emits_complete_deterministic_python_artifact_tree",
        ],
    ),
    (
        7,
        &[
            "python_emit::emits_complete_deterministic_python_artifact_tree",
            "cli::emits_complete_tree_and_verifies_exact_bytes",
        ],
    ),
    (
        8,
        &["python_runtime::generated_runtime_exercises_abi_and_provenance_loader"],
    ),
    (
        9,
        &["python_runtime::generated_runtime_exercises_abi_and_provenance_loader"],
    ),
    (
        10,
        &[
            "python_runtime::generated_runtime_exercises_abi_and_provenance_loader",
            "cli::generated_facades_enforce_contextual_and_exit_contracts",
        ],
    ),
    (
        11,
        &[
            "python_emit::emits_single_and_multiple_generic_trait_bounds",
            "python_emit::disambiguates_same_generic_name_with_different_bounds",
        ],
    ),
    (
        12,
        &[
            "python_runtime::generated_runtime_exercises_abi_and_provenance_loader",
            "cli::generated_facades_enforce_contextual_and_exit_contracts",
        ],
    ),
    (
        13,
        &["cli::generated_facades_enforce_contextual_and_exit_contracts"],
    ),
    (
        14,
        &[
            "hir::lowers_impl_state_contracts_and_old_state_fields",
            "hir::rejects_invalid_impl_state_init_and_trait_method_coverage",
        ],
    ),
    (
        15,
        &["cli::generated_facades_enforce_contextual_and_exit_contracts"],
    ),
    (
        16,
        &[
            "contract_test::derived_strategy_bytes_are_deterministic_in_module_declaration_order",
            "contract_test::derived_strategy_clause_ids_preserve_source_order",
        ],
    ),
    (
        17,
        &[
            "contract_test::derived_strategy_classifies_pure_effectful_and_never",
            "sandbox::contract_test_limits_are_fixed",
        ],
    ),
    (
        18,
        &[
            "binding::candidate_validation_public_api_uses_only_the_canonical_plan",
            "binding::validates_parameter_names_and_kinds_against_canonical_ir",
        ],
    ),
    (
        19,
        &["hir::rejects_invalid_impl_state_init_and_trait_method_coverage"],
    ),
    (
        20,
        &["binding::accepts_only_import_roots_selected_in_uv_lock"],
    ),
    (
        21,
        &["python_runtime::generated_runtime_exercises_abi_and_provenance_loader"],
    ),
    (
        22,
        &[
            "binding::validates_parameter_names_and_kinds_against_canonical_ir",
            "python_runtime::generated_runtime_exercises_abi_and_provenance_loader",
        ],
    ),
    (
        23,
        &[
            "agent_runner::codex_golden_argv_stdin_environment_and_target_write",
            "agent_runner::omp_golden_argv_prompt_environment_and_target_write",
        ],
    ),
    (
        24,
        &[
            "cli::process_bar_generation_records_unresolved_and_verified_transitions",
            "agent_runner::preexisting_hardlink_target_is_rejected",
            "agent_runner::preexisting_symlink_target_is_rejected",
        ],
    ),
    (
        25,
        &["cli::process_bar_generation_records_unresolved_and_verified_transitions"],
    ),
    (
        26,
        &[
            "binding::reports_unresolved_canonical_planned_function",
            "cli::process_bar_generation_records_unresolved_and_verified_transitions",
        ],
    ),
    (
        27,
        &["cli::process_bar_generation_records_unresolved_and_verified_transitions"],
    ),
    (
        28,
        &[
            "cli::process_bar_generation_records_unresolved_and_verified_transitions",
            "binding::reports_unreferenced_durable_implementations_as_stale",
        ],
    ),
    (
        29,
        &[
            "cli::emits_complete_tree_and_verifies_exact_bytes",
            "cli::process_bar_generation_records_unresolved_and_verified_transitions",
        ],
    ),
    (
        30,
        &[
            "binding::reports_unreferenced_durable_implementations_as_stale",
            "cli::process_bar_generation_records_unresolved_and_verified_transitions",
        ],
    ),
    (
        31,
        &[
            "transaction::tests::every_apply_fault_recovers_to_one_complete_snapshot",
            "transaction::tests::interrupted_rollback_is_idempotent",
        ],
    ),
    (
        32,
        &[
            "command::rejects_duplicate_or_invalid_options",
            "cli::json_mode_returns_one_closed_diagnostic_document_with_source_spans",
        ],
    ),
    (
        33,
        &[
            "cli::process_bar_generation_records_unresolved_and_verified_transitions",
            "examples::every_documented_example_runs_when_python3_is_available",
        ],
    ),
    (
        34,
        &[
            "formatter::lossless_formatter_normalizes_newlines_idempotently",
            "formatter::canonicalizes_spacing_indentation_lists_and_comments",
            "formatter::wraps_legal_comma_lists_at_one_hundred_columns",
        ],
    ),
    (
        35,
        &[
            "diagnostics::report_is_one_json_object_with_source_locations",
            "cli::json_mode_returns_one_closed_diagnostic_document_with_source_spans",
        ],
    ),
    (
        36,
        &[
            "cli::init_scaffolds_a_normative_project_with_pinned_uv",
            "cli::tests::scaffold_file_and_directory_fsync_faults_leave_no_target",
            "cli::tests::no_replace_publish_fault_and_collision_preserve_foreign_target",
            "cli::tests::publish_parent_fsync_fault_leaves_owned_incomplete_target_then_cleans",
            "cli::tests::temp_cleanup_remove_and_parent_fsync_are_retryable",
            "cli::tests::target_cleanup_remove_and_parent_fsync_are_ownership_checked_and_retryable",
            "cli::tests::final_commit_faults_preserve_exact_ownership_states_and_resume",
        ],
    ),
];

#[test]
fn all_36_architecture_acceptance_criteria_map_to_named_assertions() {
    assert_eq!(TRACEABILITY.len(), 36);
    for (index, (criterion, assertions)) in TRACEABILITY.iter().enumerate() {
        assert_eq!(*criterion as usize, index + 1);
        assert!(!assertions.is_empty());
        assert!(assertions.iter().all(|name| name.contains("::")));
    }
}
